base_link: 'base'

# =====================================================
left_hand:
    end_effector_name: 'left_hand'  #ee group name

    #actuated joints in end effector
    joints : ['left_gripper_l_finger_joint']

    #open position
    pregrasp_posture : [0.0095]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [-0.0125]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [-0.15, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 1.5708, 0] # 1.5707 = PI/2

    end_effector_parent_link: 'left_wrist'
# =====================================================
right_hand:
    end_effector_name: 'right_hand'  #ee group name

    #actuated joints in end effector
    joints : ['right_gripper_l_finger_joint']

    #open position
    pregrasp_posture : [0.0095]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [-0.0125]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [-0.15, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 1.5708, 0] # 1.5707 = PI/2

    end_effector_parent_link: 'right_wrist'

